language: ruby
rvm:
- 2.2.7
- 2.3.4
- 2.4.1
code_climate:
  repo_token:
    secure: 55K8ryeXRmlzUy8PtRFh1nQpZhQXo1sEySBF72fWVPMUrtj2BedCLMb5vJsXBZpW6a9p7wYktjIEHAzIH5kTxVlO1Bzm01JZxUQOTnYZDz96R5CL/dgx1G0trSe6QsGpYm3qfgEW/7NX4qr7Nydz2JpiOvzrX1I3yBOB4ILJ7oseMMXVQZ/o5yFb6FM754MkRqdwmAKPcJAfSi6BVeXfycQCAaE3+42Tr/z0lAPpWVjToH9NK0BqVqTgNcLor4INzY25JntiSRXoD9X3CZYaFwD0zfigekeOHb7B2jr64vxJwjVzxiQzNe3D1il9+b8Do/A1gwc9gouMvjPEhSzr7evIh8LviaSoIAHCkANn/jNsRYDeeK3s45eavaVkXJd53FbDQtUOl2RxBXA0CbsnmSmXtosmY2ZdHhTZNOSOJOChXPGKjpVr3kVYMEOElaMg3am3VTDSXc/eiD2CTjUl5kkoucN7FgTn1aA369iHieFWao+pzimH41As37GGDbF9tESuHAsO9MjhQPPuD3ztYpdPmQT7std60B7GttE19c37aIYVDUEhhnRLiTIskQi+6ITbZaS+wp131yIXmG7N1SqIaxGC+Scq1NOyKUGMuOqOkJdDSziksLhYh3cYjkc9UBGP80y7NtxpdzDUaM69G0IEJaPwURiwymtDxukrULk=
